/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package h61gradle;

import h61gradle.infoClass.LongestProject;
import h61gradle.infoClass.YoungestEldestWorkers;
import h61gradle.infoClass.MaxProjectCountClient;
import h61gradle.infoClass.MaxSalaryWorker;
import h61gradle.infoClass.ProjectPrices;
import h61gradle.storage.*;

import java.sql.*;
import java.util.List;

public class App {

    public static void main(String[] args) throws SQLException {

        List<MaxSalaryWorker> maxSalaryWorker = new
                DatabaseQueryService().findMaxSalaryWorker();
        System.out.println("maxSalaryWorker = "+maxSalaryWorker.toString());


        List<MaxProjectCountClient> maxProjectCountClient = new
                DatabaseQueryService().findMaxProjectCountClient();
        System.out.println("maxProjectCountClient = "+maxProjectCountClient.toString());

        List<LongestProject> longestProject = new
                DatabaseQueryService().findLongestProject();
        System.out.println("longestProject = "+longestProject.toString());

        List<YoungestEldestWorkers> youngestEldestWorkers = new
                DatabaseQueryService().findYoungestEldestWorkers();
        System.out.println("youngestEldestWorkers = "+youngestEldestWorkers.toString());

        List<ProjectPrices> projectPrices = new
                DatabaseQueryService().findProjectPrices();
        System.out.println("projectPrices = "+projectPrices.toString());
    }
}
